version: '3'

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - $PWD/modules/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123blah321
    restart: always

  tomcat:
    image: tomcat:latest
    volumes:
      - $PWD/MassBank-Project/MassBank/target/MassBank.war:/usr/local/tomcat/webapps/MassBank.war
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data  
    ports:
      - "8${TAG}:8080"
    restart: always
    depends_on:
      - mariadb
    links:
      - "mariadb:massbank_mariadb"

  maven:
    image: maven:latest
    volumes:
      - $HOME/.m2:/var/maven/.m2
      - $PWD/MassBank-Project:/project
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    user: ${CURRENT_UID}

  dbupdate:
    image: maven:latest
    volumes:
      - $PWD/MassBank-Project:/project
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data
    links:
      - "mariadb:massbank_mariadb"
