version: '3'

services:
  mariadb:
    image: mariadb:11
    volumes:
      - $PWD/modules/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: 123blah321
    restart: always
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      #start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  tomee:
    image: tomee:9-jre17-webprofile
    volumes:
      - $PWD/MassBank-Project/MassBank-web/target/MassBank.war:/usr/local/tomee/webapps/MassBank.war
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data  
      - $PWD/compose/ServerInfo.properties:/usr/local/tomee/lib/org/apache/catalina/util/ServerInfo.properties
    ports:
      - "808${TAG}:8080"
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    #environment:
      #JAVA_OPTS: -Xmx4g -Xms1g
    links:
      - "mariadb:massbank_mariadb"

  maven:
    image: maven:3.8-eclipse-temurin-17
    volumes:
      - $HOME/.m2:/var/maven/.m2
      - $PWD/MassBank-Project:/project
    working_dir: /project
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    user: ${CURRENT_UID}

  dbupdate:
    image: maven:3.8-eclipse-temurin
    volumes:
      - $PWD/MassBank-Project:/project
      - $PWD/conf/full-service.conf:/etc/massbank.conf
      - $PWD/../MassBank-data:/MassBank-data
    links:
      - "mariadb:massbank_mariadb"
