version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: massbank_mariadb
    volumes:
      - $PWD/modules/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: 123blah321
    restart: always
