DROP DATABASE IF EXISTS MassBank;
CREATE DATABASE MassBank;
USE MassBank;

--
-- Table structure for table `PEAK`
--
DROP TABLE IF EXISTS PEAK;
CREATE TABLE PEAK (
	ID          CHAR(8)  NOT NULL,
	MZ          DOUBLE   NOT NULL,
	INTENSITY   FLOAT    NOT NULL,
	RELATIVE    SMALLINT NOT NULL,
	UNIQUE(ID,MZ)
);

--
-- Table structure for table `SPECTRUM`
--
DROP TABLE IF EXISTS SPECTRUM;
CREATE TABLE SPECTRUM (
	ID          CHAR(8)      NOT NULL,
	NAME        VARCHAR(255) NOT NULL,
	ION         TINYINT      NOT NULL,
	PRECURSOR_MZ SMALLINT UNSIGNED,
	PRIMARY KEY(ID)
);

--
-- Table structure for table `TREE`
--
DROP TABLE IF EXISTS TREE;
CREATE TABLE TREE (
	NO          INT UNSIGNED      NOT NULL,
	PARENT      INT UNSIGNED      NOT NULL,
	POS         SMALLINT UNSIGNED NOT NULL,
	SON         SMALLINT          NOT NULL,
	INFO        VARCHAR(127)      NOT NULL,
	ID          CHAR(8),
	INDEX(PARENT),
	INDEX(ID)
);

--
-- Table structure for table `RECORD`
--
DROP TABLE IF EXISTS RECORD;
CREATE TABLE RECORD (
	ID            CHAR(8) NOT NULL,
	DATE          DATE,
	FORMULA       VARCHAR(30),
	EXACT_MASS    DOUBLE,
	INSTRUMENT_NO TINYINT UNSIGNED,
	SMILES        TEXT,
	IUPAC         TEXT,
	MS_TYPE       VARCHAR(8),
	PRIMARY KEY(ID),
	INDEX(FORMULA, EXACT_MASS, INSTRUMENT_NO)
);

--
-- Table structure for table `CH_NAME`
--
DROP TABLE IF EXISTS CH_NAME;
CREATE TABLE CH_NAME (
	ID              CHAR(8)      NOT NULL,
	NAME            VARCHAR(200) NOT NULL,
	INDEX(ID)
);

--
-- Table structure for table `CH_LINK`
--
DROP TABLE IF EXISTS CH_LINK;
CREATE TABLE CH_LINK (
	ID              CHAR(8)      NOT NULL,
	LINK_NAME       VARCHAR(255) NOT NULL,
	LINK_ID         VARCHAR(255) NOT NULL,
	UNIQUE(ID,LINK_NAME,LINK_ID),
	INDEX(ID)
);

--
-- Table structure for table `INSTRUMENT`
--
DROP TABLE IF EXISTS INSTRUMENT;
CREATE TABLE INSTRUMENT (
	INSTRUMENT_NO      TINYINT UNSIGNED NOT NULL,
	INSTRUMENT_TYPE    VARCHAR(50)      NOT NULL,
	INSTRUMENT_NAME    VARCHAR(200)     NOT NULL,
	PRIMARY KEY(INSTRUMENT_NO)
);

--
-- Table structure for table `MOLFILE`
--
DROP TABLE IF EXISTS MOLFILE;
CREATE TABLE MOLFILE (
	FILE              VARCHAR(8)        NOT NULL,
	NAME              VARCHAR(200)      NOT NULL,
	UNIQUE(NAME,FILE)
);

-- SPECTRUM Table Data
INSERT INTO `SPECTRUM` VALUES ('XXX00001','GABA; LC-ESI-QQ; MS2; CE:10 V; [M-H]-',-1,102);

-- PEAK Table Data
INSERT INTO `PEAK` VALUES ('XXX00001',58.5,39604,1),('XXX00001',73.2,14851.5,1),('XXX00001',83.9,975248,16),('XXX00001',101.3,103960,2),('XXX00001',102,5.93961e+07,999);

-- RECORD Table Data
INSERT INTO `RECORD` VALUES ('XXX00001','2011.12.20 (Created 2007.07.07)','C4H9NO2',103.06333,1,'NCCCC(O)=O','InChI=1S/C4H9NO2/c5-3-1-2-4(6)7/h1-3,5H2,(H,6,7)','MS2');

-- CH_NAME Table Data
INSERT INTO `CH_NAME` VALUES ('XXX00001','4-Aminobutanoate'),('XXX00001','4-Aminobutanoic acid'),('XXX00001','4-Aminobutylate'),('XXX00001','4-Aminobutyrate'),('XXX00001','4-Aminobutyric acid'),('XXX00001','GABA'),('XXX00001','gamma-Aminobutyric acid');

-- INSTRUMENT Table Data
INSERT INTO `INSTRUMENT` VALUES (1,'LC-ESI-QQ','API3000, Applied Biosystems');

-- TREE Table Data
INSERT INTO `TREE` VALUES (1,0,1,1,'MassBank',NULL),(619,1,1,1,'LC-ESI-QQ',NULL),(1071,619,1,1,'MW 103',NULL),(1072,1071,1,1,'C4H9NO2',NULL),(1096,1072,1,1,'GABA',NULL),(1103,1096,1,1,'[M-H]-',NULL),(1104,1103,1,-1,'MS2  /  10 V','XXX00001');

-- MOLFILE Table Data
INSERT INTO `MOLFILE` VALUES ('XX000001','GABA');


DROP DATABASE IF EXISTS MassBank_General;
CREATE DATABASE MassBank_General;
USE MassBank_General;

--
-- Table structure for table `JOB_INFO`
--
DROP TABLE IF EXISTS JOB_INFO;
CREATE TABLE JOB_INFO (
	JOB_ID            VARCHAR(36)       NOT NULL,
	STATUS            VARCHAR(20)       NOT NULL,
	TIME_STAMP        VARCHAR(19)       NOT NULL,
	SESSION_ID        VARCHAR(32),
	IP_ADDR           VARCHAR(15),
	MAIL_ADDR         VARCHAR(50),
	QUERY_FILE_NAME   TEXT,
	QUERY_FILE_SIZE   INT(10) UNSIGNED,
	TEMP_FILE_NAME    TEXT,
	SEARCH_PARAM      TEXT,
	RESULT            LONGTEXT,
	PRIMARY KEY(JOB_ID)
);


GRANT ALL PRIVILEGES ON *.* TO bird@localhost IDENTIFIED BY 'bird2006' WITH GRANT OPTION;
